config/routes.rb
Comics::Application.routes.draw do

  resources :users, only: [:show] do
    member do
      get 'token'
      get 'get_new_token'
    end
  end
  resources :users do
    resources :publishers, only: [:index, :show]
    resources :issues, only: [:show, :update]
    resources :volumes, only: [:show]
    resources :characters, only: [:index, :show]
    resources :people, only: [:index, :show]
    resources :subscriptions, only: [:index, :create, :destroy]
    resources :collected_editions, only: [:show, :update, :new, :create]
  end
  get 'users/:user_id/collected_editions/new/:id', to: 'collected_editions#new', as: 'new_user_collected_edition_id'

  get 'users/:user_id/issues/:id/:variant_id', to: 'issues#show', as: 'user_variant'
  post 'users/:user_id/issues/:id/add', to: 'users#add_existing_issue', as: 'user_add_existing_issue'

  post 'add_issue', to: 'users#add_issue'
  get 'add_collected_edition', to: 'collected_editions#add_collected_edition'
  post 'add_variant', to: 'users#add_variant'
  post 'add_volume', to: 'users#add_subscription'
  post 'remove_volume', to: 'users#remove_subscription'
  get 'get_username', to: 'users#get_username'
  get 'get_number_of_issues', to: 'users#get_number_of_issues'
  get 'volume_subscribed', to: 'users#volume_subscribed'

  get 'update_all_issues', to: 'issues#update_all'

  get 'sessions/new', as: 'login'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'sessions#new'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :volume

  has_many :collections
  has_many :users, through: :collections
  has_many :creators
  has_and_belongs_to_many :characters, -> { uniq }

  has_attached_file :cover

  validates :cv_id, presence: true, uniqueness: true
  validates :issue_number, presence: true
  validates :site_detail_url, presence: true
  validates :volume_id, presence: true
  validates :cover, attachment_presence: true

  delegate :name, to: :volume, prefix: true
  delegate :publisher, to: :volume

  default_scope { order("CAST(issue_number AS DECIMAL(6,2)) ASC") }

  ID_PREFIX = '4000-'

  def to_s
    "#{self.volume_name}, ##{self.issue_number} - #{self.name}"
  end

  def cover_from_url(url)
    self.cover = URI.parse(url)
  end

  def self.cv_find_or_create(cv_id)
    cv_id = cv_id.start_with?(ID_PREFIX) ? cv_id : ID_PREFIX + cv_id
    issue = Issue.where(cv_id: cv_id).first
    unless issue
      result = ComicVine.find_issue(cv_id)['results']
      issue = Issue.new
      issue.cv_id = cv_id
      issue.set_properties(result)
    end
    issue
  end

  def cv_update
    result = ComicVine.find_issue(cv_id)['results']
    self.set_properties(result)
  end

  def set_properties(result)
    self.name = result['name']
    self.issue_number = result['issue_number']
    self.site_detail_url = result['site_detail_url']
    self.store_date = result['store_date']
    self.volume = Volume.cv_find_or_create(result['volume']['id'].to_s)
    self.cover_from_url(result['image']['small_url'])
    result['character_credits'].each do |character|
      self.characters << Character.from_cv_id_and_name(character['id'].to_s, character['name'])
    end
    result['person_credits'].each do |p|
      role = Role.where(name: p['role']).first
      if role
        person = Person.from_cv_id_and_name(p['id'].to_s, p['name'])
        creator = Creator.new
        creator.person = person
        creator.issue = self
        creator.role = role
        creator.save
      end
    end
    self.save
  end

  def self.update_all
    Issue.all.each_with_index do |issue, index|
      issue.cv_update
      Delayed::Worker.logger.debug("Updated #{index+1} issues")
      # sleep to stay under API limit
      sleep 2
    end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
    @user = User.where(id: params[:user_id]).first
    @issue = Issue.where(id: params[:id]).first
    @variant = Collection.where(id: params[:variant_id]).first if params[:variant_id]
  end

  def update
    @user = User.where(id: params[:user_id]).first
    @issue = Issue.where(id: params[:id]).first

    @issue.cv_update

    respond_to do |format|
      format.html { redirect_to user_issue_url(@user, @issue), notice: 'Issue updated' }
    end
  end

  def update_all
    Issue.delay.update_all
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Issues updating."}
    end
  end

end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/show.html.erb
<h2><%= @variant.nil? ? @issue.to_s : @variant.to_s %></h2>
<p>
  <%= link_to 'Update Details', user_issue_path(@user, @issue), method: 'put', class: 'btn btn-primary' %>
  <%= link_to 'Add Issue to Collection', user_add_existing_issue_path(@user, @issue), method: 'post', class: 'btn btn-primary' unless @user.issues.include?(@issue) %>
</p>

<div class="row">
  <div class="col-md-3 col-md-push-9">
    <% image = @variant.nil? ? @issue.cover.url : @variant.variant.url %>
    <%= link_to image, class: 'thumbnail fancybox' do %>
      <%= image_tag(image) %>
    <% end %>
  </div>

  <div class="col-md-9 col-md-pull-3">
    <div class='list-group'>
      <%= link_to @issue.volume, user_volume_path(@user, @issue.volume), class: 'list-group-item' %>
    </div>

    <div class='list-group'>
      <p>Creative Team</p>
      <% @issue.creators.each do |creator| %>
        <%= link_to user_person_path(@user, creator.person), class: 'list-group-item' do %>
          <%= creator.person_name %>,
          <%= creator.role_name %>
        <% end %>
      <% end %>
    </div>

    <div class='list-group'>
      <p>Characters</p>
      <% @issue.characters.each do |character| %>
          <%= link_to character.name, user_character_path(@user, character), class: 'list-group-item' %>
      <% end %>
    </div>
  </div>
</div>