config/routes.rb
Comics::Application.routes.draw do

  resources :users, only: [:show] do
    member do
      get 'token'
      get 'get_new_token'
    end
  end
  resources :users do
    resources :publishers, only: [:index, :show]
    resources :issues, only: [:show, :update]
    resources :volumes, only: [:show]
    resources :characters, only: [:index, :show]
    resources :people, only: [:index, :show]
    resources :subscriptions, only: [:index, :create, :destroy]
    resources :collected_editions, only: [:show, :update, :new, :create]
  end
  get 'users/:user_id/collected_editions/new/:id', to: 'collected_editions#new', as: 'new_user_collected_edition_id'

  get 'users/:user_id/issues/:id/:variant_id', to: 'issues#show', as: 'user_variant'
  post 'users/:user_id/issues/:id/add', to: 'users#add_existing_issue', as: 'user_add_existing_issue'

  post 'add_issue', to: 'users#add_issue'
  get 'add_collected_edition', to: 'collected_editions#add_collected_edition'
  post 'add_variant', to: 'users#add_variant'
  post 'add_volume', to: 'users#add_subscription'
  post 'remove_volume', to: 'users#remove_subscription'
  get 'get_username', to: 'users#get_username'
  get 'get_number_of_issues', to: 'users#get_number_of_issues'
  get 'volume_subscribed', to: 'users#volume_subscribed'

  get 'update_all_issues', to: 'issues#update_all'

  get 'sessions/new', as: 'login'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'sessions#new'

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :volumes
  
  validates :cv_id, presence: true, uniqueness: true
  validates :name, presence: true

  default_scope { order(:name) }

  ID_PREFIX = '4010-'

  def self.from_cv_id_and_name(cv_id, name)
    cv_id = cv_id.start_with?(ID_PREFIX) ? cv_id : ID_PREFIX + cv_id
    publisher = Publisher.where(cv_id: cv_id).first
    unless publisher
      publisher = Publisher.new
      publisher.cv_id = cv_id
      publisher.name = name
      publisher.save
    end
    publisher
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @user = User.where(params[:user_id]).first
    @publishers = @user.publishers.sort{|a,b| a.name.downcase <=> b.name.downcase }
  end

  def show
    @user = User.where(params[:user_id]).first
    @publisher = @user.publishers.select{|publisher| publisher.id.to_s == params[:id]}.first
    @volumes = @publisher.volumes
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/index.html.erb
<h2>Publishers In Collection</h2>

<ul>
  <% @publishers.each do |publisher| %>
    <li>
      <%= link_to publisher.name, user_publisher_path(@user, publisher) %>
      (<%= pluralize(publisher.volumes.size, 'Volume') %>)
    </li>
  <% end %>
</ul>

app/views/publishers/show.html.erb
<h2><%= @publisher.name %></h2>

<div class='col-md-12'>
  <div class='list-group'>
    <% @volumes.each do |volume| %>
      <%= link_to user_volume_path(@user, volume), class: 'list-group-item' do %>
        <%= volume.to_s %><span class='badge'><%= @user.issues_by_volume(volume).size %></span>
      <% end %>
    <% end %>
  </div>
</div>