config/routes.rb
Comics::Application.routes.draw do

  resources :users, only: [:show] do
    member do
      get 'token'
      get 'get_new_token'
    end
  end
  resources :users do
    resources :publishers, only: [:index, :show]
    resources :issues, only: [:show, :update]
    resources :volumes, only: [:show]
    resources :characters, only: [:index, :show]
    resources :people, only: [:index, :show]
    resources :subscriptions, only: [:index, :create, :destroy]
    resources :collected_editions, only: [:show, :update, :new, :create]
  end
  get 'users/:user_id/collected_editions/new/:id', to: 'collected_editions#new', as: 'new_user_collected_edition_id'

  get 'users/:user_id/issues/:id/:variant_id', to: 'issues#show', as: 'user_variant'
  post 'users/:user_id/issues/:id/add', to: 'users#add_existing_issue', as: 'user_add_existing_issue'

  post 'add_issue', to: 'users#add_issue'
  get 'add_collected_edition', to: 'collected_editions#add_collected_edition'
  post 'add_variant', to: 'users#add_variant'
  post 'add_volume', to: 'users#add_subscription'
  post 'remove_volume', to: 'users#remove_subscription'
  get 'get_username', to: 'users#get_username'
  get 'get_number_of_issues', to: 'users#get_number_of_issues'
  get 'volume_subscribed', to: 'users#volume_subscribed'

  get 'update_all_issues', to: 'issues#update_all'

  get 'sessions/new', as: 'login'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'sessions#new'

end

app/models/volume.rb
class Volume < ActiveRecord::Base
  belongs_to :publisher
  has_many :users, through: :issues
  has_many :issues
  has_many :collected_editions
  has_many :subscriptions

  validates :cv_id, presence: true, uniqueness: true
  validates :name, presence: true
  validates :publisher_id, presence: true
  validates :start_year, presence: true

  default_scope { order(:name) }

  ID_PREFIX = '4050-'

  def self.cv_find_or_create(cv_id)
    cv_id = cv_id.start_with?(ID_PREFIX) ? cv_id : ID_PREFIX + cv_id
    volume = Volume.where(cv_id: cv_id).first
    unless volume
      result = ComicVine.find_volume(cv_id)['results']
      volume = Volume.new
      volume.cv_id = cv_id
      volume.name = result['name']
      volume.start_year = result['start_year']
      # volume.publisher = Publisher.cv_find_or_create(result['publisher']['id'])
      volume.publisher = Publisher.from_cv_id_and_name(result['publisher']['id'].to_s,result['publisher']['name'])
      volume.save
    end
    volume
  end

  def to_s
    "#{self.name} (#{start_year})"
  end

  def number_issues
    self.issues.size
  end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  def show
    @user = User.where(id: params[:user_id]).first
    @volume = Volume.where(id: params[:id]).first
    @issues = @user.issues_by_volume(@volume)
    @collected_editions = @user.collected_editions_by_volume(@volume)
  end
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/volumes/show.html.erb
<h2><%= @volume.to_s %></h2>

<p>
  <% if @user.is_subscribed?(@volume.cv_id) %>
    <%= link_to 'Unsubscribe', user_subscription_path(@user, @volume), method: :delete, class: 'btn btn-primary' %>
  <% else %>
      <%= link_to 'Subscribe', user_subscriptions_path(@user, id: @volume.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
</p>

<div class='col-md-6'>
  <h2>Issues</h2>
  <div class='list-group'>
    <% @issues.each do |issue| %>
      <% collections = @user.collections.where(issue: issue).load %>

      <% collections.each do |collection| %>
        <% if collection.is_variant? %>
          <%= link_to collection.to_s, user_variant_path(@user, issue, collection.id), class: 'list-group-item' %>
        <% else %>
          <%= link_to issue.to_s, user_issue_path(@user, issue), class: 'list-group-item' %>
        <% end %>
      <% end %>

    <% end %>
  </div>
</div>

<div class='col-md-6'>
  <h2>Collected Editions</h2>
  <div class='list-group'>
    <% @collected_editions.each do |collected_edition| %>
      <%# collections = @user.collections.where(issue: issue).load %>

      <!-- <%# collections.each do |collection| %>
        <%# if collection.is_variant? %>
          <%#= link_to collection.to_s, user_variant_path(@user, issue, collection.id), class: 'list-group-item' %>
        <%# else %> -->
          <%= link_to collected_edition.to_s, user_collected_edition_path(@user, collected_edition), class: 'list-group-item' %>
        <!-- <%# end %> -->
      <%# end %>

    <% end %>
  </div>
</div>