config/routes.rb
Comics::Application.routes.draw do

  resources :users, only: [:show] do
    member do
      get 'token'
      get 'get_new_token'
    end
  end
  resources :users do
    resources :publishers, only: [:index, :show]
    resources :issues, only: [:show, :update]
    resources :volumes, only: [:show]
    resources :characters, only: [:index, :show]
    resources :people, only: [:index, :show]
    resources :subscriptions, only: [:index, :create, :destroy]
    resources :collected_editions, only: [:show, :update, :new, :create]
  end
  get 'users/:user_id/collected_editions/new/:id', to: 'collected_editions#new', as: 'new_user_collected_edition_id'

  get 'users/:user_id/issues/:id/:variant_id', to: 'issues#show', as: 'user_variant'
  post 'users/:user_id/issues/:id/add', to: 'users#add_existing_issue', as: 'user_add_existing_issue'

  post 'add_issue', to: 'users#add_issue'
  get 'add_collected_edition', to: 'collected_editions#add_collected_edition'
  post 'add_variant', to: 'users#add_variant'
  post 'add_volume', to: 'users#add_subscription'
  post 'remove_volume', to: 'users#remove_subscription'
  get 'get_username', to: 'users#get_username'
  get 'get_number_of_issues', to: 'users#get_number_of_issues'
  get 'volume_subscribed', to: 'users#volume_subscribed'

  get 'update_all_issues', to: 'issues#update_all'

  get 'sessions/new', as: 'login'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='navbar navbar-inverse navbar-static-top' role='navigation'>
    <div class='container'>
      <div class='navbar-header'>
        <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
          <span class="navbar-link">Menu</span>
        </button>
        <%= link_to 'Comics', root_url, class: 'navbar-brand' %>
      </div>

      <div class='collapse navbar-collapse'>
        <ul class='nav navbar-nav'>
          <li>
            <%= link_to 'Home', user_path(@current_user) if @current_user %>
          </li>
          <li>
            <%= link_to 'Subscriptions', user_subscriptions_path(@current_user) if @current_user %>
          </li>
        </ul>
        <ul class='nav navbar-nav navbar-right'>
          <% if @current_user %>
            <li class='dropdown'>
              <a href="#" class='dropdown-toggle' data-toggle='dropdown'>
                <%= @current_user.name %>
                <b class='caret'></b>
              </a>
              <ul class='dropdown-menu'>
                <li>
                  <%= link_to 'Sign out', signout_path %>
                </li>
                <li>
                  <%= link_to 'Update All Issues', update_all_issues_path %>
                </li>
                <li>
                  <%= link_to 'Chrome Extension Token', token_user_path(@current_user) %>
                </li>
              </ul>

            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <%= render partial: "shared/flash_messages", flash: flash %>
    <div class='row'>
      <%= yield %>
    </div>
  </div>

</body>
</html>